print("         *           ")
print("        /.\          ")
print("       /o..\         ")
print("       /..o\         ")
print("      /.o..o\        ")
print("      /...o.\        ")
print("     /.o.....\       ")
print("     ^^^[_]^^^       ")
print("Code is read much more often than it is written. — Guido van Rossum")